services:
  elasticsearch:
    image: elasticsearch:8.18.2
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - xpack.security.enabled=false
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  cortex:
    image: thehiveproject/cortex
    environment:
      - docker_job_directory=${job_directory}
      - job_directory=${job_directory}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./application.conf:/etc/cortex/application.conf
      - ${job_directory}:${job_directory}
    depends_on:
      - elasticsearch
    ports:
      - "0.0.0.0:9001:9001"

  n8n:
    build: .
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    volumes:
      - ../scripts:/scripts
      - ../email_phishing:/data/eml
      - n8n_data:/home/node/.n8n
    restart: unless-stopped
    depends_on:
      - cortex

volumes:
  n8n_data:
